"""Initial migration

Revision ID: bb7b8062918d
Revises: 
Create Date: 2023-10-29 11:00:27.631817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7b8062918d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.Date(), nullable=True))
        batch_op.drop_column('returned')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###
